### ISSUE TITLE
Bookmarks not saving correctly.

### ISSUE THREAD

**Issue by forsythetony** [forsythetony/CollegeComparison#10]
Either the bookmarks aren't saving correctly or they're not being loaded correctly. It could also be an issue specific to running the app in the simulator.

**Comment by JMV2112** [comment]
I'm out of the country right now and trying to work on app but i pulled and now having conflicts within the storyboard and CollegeDetailTableViewController.m. I don't want to mess anything up so i'm thinking that I might just reclone the project to my desktop? What do you think?

**Comment by forsythetony** [comment]
Yea, I guess that'd be best. If you can wait I'd be able to take a look at it later tonight when I get to my mac, but it could also be an issue specific to you because Maura just pulled it down and ran it.

**Comment by JMV2112** [comment]
Yea it's an issue with my branch
