### ISSUE TITLE
Navigation Bar Title

### ISSUE THREAD

**Issue by maurahoward** [forsythetony/CollegeComparison#31]
The title of each screen on the navigation bar (Results, Filter, Details) needs to be   in white in Avenir.

**Comment by forsythetony** [comment]
This is currently how the font for all titles throughout the entire app get set. 

``` Objective-C
[[UINavigationBar appearance] setTitleTextAttributes:[NSDictionary dictionaryWithObjectsAndKeys:
                                                          [UIColor whiteColor], NSForegroundColorAttributeName,
                                                          [UIFont fontWithName:@"Avenir-Book" size:24.0], NSFontAttributeName,
                                                          nil]];
```

Which ends up looking like this

![image](https://f.cloud.github.com/assets/5825210/1895219/df2fc4ae-7b1d-11e3-8fe8-596670cadae6.png)

**Comment by JMV2112** [comment]
We can make a global method to call this within every view controller right? If so, that would be the easiest way to set these attributes and have it take in one parameter which would be the title.  What do you think?

**Comment by forsythetony** [comment]
This is set within the app delegate and applied to all navbars in the application. You might be able to override it within a particular view controller though.

**Comment by forsythetony** [comment]
Can we close this issue?
